create table if not exists public.content_drafts (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  user_id bigint,
  format text not null default 'post',
  idea text not null,
  content text not null,
  status text not null default 'Draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  telegram_message_id bigint
);

create index if not exists content_drafts_chat_id_idx on public.content_drafts(chat_id);
create index if not exists content_drafts_status_idx on public.content_drafts(status);
